xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start&
xdbdmgr stop&
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
xdbdmgr start
