/*
 * XdbdLocalClient.h
 *
 *  Created on: 30. okt. 2015
 *      Author: miran
 */

#pragma once

#include <sys/mman.h>
#include "XdbdRunningContext.h"
#include "XdbdRunnable.h"
#include "XdbdWorkingClient.h"
#include "XdbdClientHandler.h"
#include "XdbdMessages.h"
#include "XdbdCommon.h"
#include "XdbdShmSegment.h"
#include <set>
using namespace std;

namespace xml_db_daemon
{

/*! @brief UNIX domain client class
 *
 *  this class represents communication channel between local
 *  UNIX domain client and XML DB server
 *
 */
class	XdbdLocalClient : public XdbdWorkingClient
{
private:
	typedef set < XdbdShmSegment* >	shmset;	//!< type representing self-ordered collection of shared memory segments
public:
	XdbdLocalClient(XdbdRunningContext* ctx, int fd, XdbdRunnable* mainThread);
	virtual ~XdbdLocalClient();
	void	first_half_callback (void* data);
	void	second_half_callback (void* data);

	/*! @brief obtain shared memory object
	 *
	 *  given shared memory ticket, obtain associated shared memory object
	 *
	 *  @param ticket long number representing shared memory object reference
	 *
	 */
	inline XdbdShmSegment*	shmSegment (u_long ticket) { return (m_shmset.find((XdbdShmSegment*)ticket) == m_shmset.end()) ? 0 : (XdbdShmSegment*)ticket; }
	XdbdShmSegment*	deleteShmSegment (u_long ticket);

private:
	fd_handler(HandleLocalClient, XdbdLocalClient)	//!< local client I/O handler

	void Release ();
	void PostSqlReply (XdbdReply* req);
	void PostSqlErrorResponse (XdbdErrorType errorType, XdbdErrorCode errorCode, const char* errorMessage);

	void HandleSqlConnectRequest (XdbdRequest* req);
	void HandleSqlDisconnectRequest (XdbdRequest* req);
	void HandleSqlCreateStatementRequest (XdbdRequest* req);
	void HandleSqlDeleteStatementRequest (XdbdRequest* req);
	void HandleSqlPrepareRequest (XdbdRequest* req);
	void HandleSqlExecuteRequest (XdbdRequest* req);
	void HandleSqlExecuteDirectRequest (XdbdRequest* req);
	void HandleSqlUnknownRequest (XdbdRequest* req);

	void DisplayXdbdRequest (XdbdRequest* req);
	void DisplayXdbdReply (XdbdReply* rpl);

	void PostSqlConnectReply (XdbdRequest* req);
	void PostSqlDisconnectReply (XdbdRequest* req);
	void PostSqlCreateStatementReply (XdbdRequest* req, XdbdShmSegment* shmSegment);
	void PostSqlDeleteStatementReply (XdbdRequest* req, XdbdShmSegment* shmSegment);
	void PostSqlPrepareReply (XdbdRequest* req, XdbdShmSegment* shmSegment);
	void PostSqlExecuteReply (XdbdRequest* req, XdbdShmSegment* shmSegment);
	void PostSqlExecuteDirectReply (XdbdRequest* req, XdbdShmSegment* shmSegment);
	void PostSqlUnknownReply (XdbdRequest* req);

private:
	static const char*	g_errorString[];	//!< error strings
	static int g_reqIndex;	//!< request index

private:
	XdbdRunningContext*	m_ctx;	//!< I/O multiplexer governing this client

	bool	m_connected;	//!< SQL connected?
	int	m_fd;

	shmset	m_shmset;	//!< set of all SMH segments collected so far by SQL statements created by this client

	void*	m_localHandler;	//!< I/O handler reference

	int	m_intSize;	//!< size of XDR integer representation

	u_char*	m_inputBuffer;	//!< input buffer holding incoming requests
	u_char*	m_inputPtr;	//!< input buffer read head
	u_char*	m_inputEnd;	//!< input buffer far end

	u_char*	m_outputBuffer;	//!< output buffer holding outgoing replies
	u_char*	m_outputPtr;	//!< output buffer write head
	u_char*	m_outputEnd;	//!< output buffer far end

	XdbdError*	m_errorList;	//!< list of error messages generated by executing SQL statement
};

/*! brief local client activation message
 *
 *  this class represents local client 'activation' message generated
 *  by main thread of working entity. This message is sent to selected
 *  client driver thread. After this message has been processed by that
 *  thread client has become 'activated': newly created XdbdLocalClient
 *  is associated with it and I/O handler is registered with I/O multiplexer
 *  residing in selected client driver thread.
 *
 */
class XdbdLocalClientActivationMessage : public XdbdRunningContextMsg
{
public:
	/*! @brief UNIX domain client activation message constructor
	 *
	 *  @param localClientFd FD obtained by calling accept() system call in main worker thread
	 *  @param clientDriver reference to current client driver thread
	 *
	 */
	XdbdLocalClientActivationMessage (int localClientFd, void* clientDriver) : XdbdRunningContextMsg () { m_localClientFd = localClientFd; m_clientDriver = clientDriver; }
	/*! @brief UNIX domain client activation message destructor
	 *
	 */
	virtual ~XdbdLocalClientActivationMessage () {}
	virtual int	Invoke (XdbdRunningContext* ctx);
	/*! @brief obtain this class name
	 *
	 */
	virtual const char* Name () { return "XdbdLocalClientActivationMessage"; }
private:
	int	m_localClientFd;	//!< UNIX domain socket FD associated with activated client
	void*	m_clientDriver;	//!< client driver thread governing client communication
};

/*! @brief UNIX domain client response message
 *
 *  all client response messages are actually created by working threads processing
 *  SQL jobs. Since these threads does not know how to communicate these responses,
 *  they are sent to client driver threads associated with these clients which then
 *  process them. This class represents messages sent from working to client driver
 *  threads.
 *
 */
class XdbdLocalClientResponseMessage : public XdbdRunningContextMsg
{
public:
	/*! @brief UNIX domain client response message constructor
	 *
	 *  @param localClient object representing UNIX domain client
	 *  @param data general reference of message generated by working thread
	 *  @param clientDriver client driver thread governing client communication
	 *
	 */
	XdbdLocalClientResponseMessage (XdbdLocalClient* localClient, void* data, void* clientDriver) : XdbdRunningContextMsg () { m_localClient = localClient; m_data = data; m_clientDriver = clientDriver; }
	/*! @brief UNIX domain client response message destructor
	 *
	 */
	virtual ~XdbdLocalClientResponseMessage () {}
	virtual int	Invoke (XdbdRunningContext* ctx);
	/*! @brief obtain this class name
	 *
	 */
	virtual const char* Name () { return "XdbdLocalClientResponseMessage"; }
private:
	XdbdLocalClient*	m_localClient;	//!< UNIX domain client object reference
	void*	m_data;	//!< general reference of message generated by working thread
	void*	m_clientDriver;	//!< client driver thread governing client communication
};

} /* namespace xml_db_daemon */
